CREATE TABLE Users(
    UserID VARCHAR(255) NOT NULL,
    Rating INT UNSIGNED NOT NULL,
    Location VARCHAR(255),
    Country VARCHAR(255),
    PRIMARY KEY (UserID)
);

CREATE TABLE Auctions(
    ItemID BIGINT UNSIGNED NOT NULL,
    SellerID VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    StartTime TIMESTAMP NOT NULL,
    EndTime TIMESTAMP NOT NULL,
    StartPrice DECIMAL(8,2) NOT NULL,
    BuyPrice DECIMAL(8,2),
    Description VARCHAR(4000) NOT NULL,
    PRIMARY KEY (ItemID),
    FOREIGN KEY (SellerID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Categories(
    CategoryID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    PRIMARY KEY (CategoryID)
);

CREATE TABLE Bids(
    ItemID  BIGINT UNSIGNED NOT NULL,
    BidderID VARCHAR(255) NOT NULL,
    Time TIMESTAMP NOT NULL,
    Amount DECIMAL(8,2) NOT NULL,
    PRIMARY KEY (ItemID, BidderID, Time),
    FOREIGN KEY (BidderID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES Auctions(ItemID) ON DELETE CASCADE
);

CREATE TABLE AuctionsCategories(
    ItemID BIGINT UNSIGNED NOT NULL,
    CategoryID INT UNSIGNED NOT NULL,
    PRIMARY KEY (ItemID, CategoryID),
    FOREIGN KEY (ItemID) REFERENCES Auctions(ItemID) ON DELETE CASCADE,
    FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID) ON DELETE CASCADE
);
