LOAD DATA LOCAL INFILE 'users.dat' INTO TABLE Users FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'auctions.dat' INTO TABLE Auctions FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'categories.dat' INTO TABLE Categories FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'bids.dat' INTO TABLE Bids FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'auctionscategories.dat' INTO TABLE AuctionsCategories FIELDS TERMINATED BY '|*|';